@extends('layouts.navbar')
@section('title', 'Inicio')
@section('content')

    <div class="container" style="margin-top: 80px;">
        <h1>Hola amigos</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia saepe delectus iure porro, fugiat voluptatibus earum adipisci soluta vel molestias quidem, ut recusandae nam cum ad qui nesciunt incidunt unde.
        Est voluptatem cupiditate architecto nemo reiciendis totam, praesentium iusto. Maiores aut nobis enim omnis incidunt quia voluptate accusantium voluptatibus inventore sit dolor obcaecati, maxime ex nemo delectus quae, odit quisquam!
        Voluptatibus vel amet modi nesciunt sed, molestiae porro totam velit maiores vitae sit cum, numquam asperiores fugit cupiditate molestias quis culpa! Autem enim commodi debitis voluptates ut, sapiente eligendi architecto.
        Ullam, nisi dolore placeat sapiente impedit magnam esse. Voluptas accusantium ipsam, reiciendis sapiente, labore totam qui soluta vel doloribus tempora quasi consequuntur obcaecati eaque beatae neque sunt sint facilis quas!
        Tempore illum ipsam impedit voluptatum sit numquam optio adipisci, aliquid ad nihil quibusdam eos quod maiores perferendis? Qui non ad odit laborum atque est eius, ratione nostrum, eaque, adipisci distinctio.
        Atque tempora, est adipisci deserunt quos, ex sit beatae alias ut obcaecati voluptates voluptatum vel officiis incidunt, accusantium architecto explicabo laborum magni eaque cupiditate veritatis corrupti? Modi incidunt in eum.
        Itaque eum velit adipisci esse quibusdam, corporis quod sit laudantium facere molestiae provident molestias, asperiores fugit, officiis eligendi quam. Quod dolore neque, excepturi fugiat eveniet quidem fuga autem pariatur quis!
        Autem, deserunt. Velit praesentium aliquid repellendus aliquam at repellat, blanditiis voluptas illum esse maiores consequuntur rem qui? Earum fuga pariatur dignissimos ex quo, in laboriosam provident qui? Impedit, fugiat iste.
        Rem quis quae pariatur animi officiis natus voluptate sint dolores doloremque. Consectetur in, amet exercitationem beatae ex maiores nisi delectus modi eius molestiae illum quidem suscipit magni! Nihil, voluptate ab!
        Ex beatae, quod obcaecati ullam minus reiciendis tempore natus animi eum dolore cumque reprehenderit ipsam nobis, itaque repudiandae optio nisi consequatur ea mollitia modi. Ratione quidem dolorum vero laboriosam numquam.
        Quibusdam dolorem totam, perspiciatis saepe illo amet nobis possimus tenetur tempora magni et unde delectus deleniti temporibus at earum eligendi distinctio recusandae inventore veritatis non fugiat minima! Modi, possimus natus!
        Ab molestiae dicta voluptatum, eligendi culpa fugit, eos in voluptas veniam autem doloremque sit sunt impedit mollitia laudantium quaerat beatae enim. Fugiat quaerat ad blanditiis expedita distinctio! Hic, atque ducimus!
        Quo, unde voluptatem sapiente omnis impedit quidem veniam quasi culpa expedita aut doloribus quae non corrupti, numquam repellat est ipsam optio deleniti architecto suscipit iusto quod corporis iure tempore? Ex.
        Debitis architecto laboriosam consectetur eum est, tenetur totam quos in aspernatur amet praesentium. Vel, praesentium! Quidem earum porro eos corrupti quaerat sit vero voluptas pariatur nulla dolor natus, cupiditate labore.
        Aperiam ab autem officia? Eligendi explicabo ullam nobis, tenetur saepe amet maxime accusamus repudiandae quas, beatae minima! Ad iusto quam necessitatibus ea commodi quaerat recusandae vitae minus, labore soluta accusamus.
        Repellat voluptatem nihil delectus illo voluptates omnis itaque optio tenetur. Ratione quaerat, odio doloribus nesciunt mollitia facilis architecto odit! Quasi dolores accusamus enim, voluptate nostrum fuga veniam suscipit at? Beatae.
        Hic quisquam voluptates dolore quod velit iusto dolorum exercitationem? Voluptatibus magni ut quod, beatae eaque similique aliquam laborum natus quo minus autem velit, pariatur accusantium, quasi sit aut quia! Voluptas?
        Distinctio officiis quas accusamus magni maiores blanditiis consequuntur nulla voluptatum dolor, culpa adipisci reiciendis sunt, perspiciatis nesciunt quibusdam ad consectetur corrupti quis deleniti quaerat autem saepe, itaque error illum. Sequi?
        Voluptatibus nam sequi, perspiciatis nihil facere, ut iste blanditiis dolore eius itaque hic aliquam saepe ullam, corporis inventore placeat nulla provident eaque dolorum in alias adipisci? Doloribus laborum consequuntur rerum.
        Impedit cupiditate reiciendis libero maiores iusto accusantium corrupti. Architecto velit minus natus explicabo impedit exercitationem repellat. Error, fuga tempora et odio nulla unde maiores velit dolorem harum sapiente, quis quisquam?
        Hic dolore assumenda, excepturi pariatur perspiciatis ipsam omnis facilis tenetur rem aut asperiores consequatur beatae praesentium nam dolor distinctio delectus minus provident, repellat modi accusantium tempore? Eveniet nisi ducimus in!
        Nesciunt mollitia consequuntur alias natus exercitationem cum inventore excepturi repellat illum reprehenderit, quod id ipsa sequi at? Exercitationem hic, ipsa asperiores laborum voluptatem soluta facilis quo natus officiis officia sint.
        Molestias hic voluptatem sapiente atque incidunt, inventore praesentium voluptatum quod impedit iure dolores, doloribus id ipsa officia magnam! Fuga magni est voluptates aperiam illum id cupiditate amet quasi! Non, tempore.
        Rem dolorum quas doloremque incidunt maiores, eaque nisi facilis nihil! Officiis, quas inventore consequatur odit, praesentium eaque ipsa quibusdam dolore nostrum laboriosam dicta a adipisci, repudiandae unde iure fuga reprehenderit.
        Saepe obcaecati consequatur sint impedit alias tempore dolorum unde minus quidem? Quo, possimus recusandae! Culpa nihil, inventore placeat repudiandae laboriosam sint quis! Cupiditate ratione similique quidem. Odit tempore labore provident!
        Asperiores, ab ducimus at hic rem quidem totam saepe accusantium voluptatem tenetur ad alias earum praesentium voluptatum qui dolorem fugit veniam ipsum perferendis quasi! Non neque repellendus suscipit atque veniam.
        Fuga cupiditate, odit atque consequuntur fugit ipsum quis vero autem ea, tempora eveniet perferendis, similique obcaecati dignissimos? Atque molestiae nulla unde repudiandae esse est aperiam, vero, dolore delectus recusandae commodi!
        Sed itaque cupiditate deserunt quod, libero fugit saepe minus. Nulla laborum tempora harum distinctio iusto? Corrupti, necessitatibus! Dolorem magni aperiam nulla? Facere a, eos obcaecati expedita quaerat in laborum corporis?
        Aliquid id dolor assumenda non? Aperiam suscipit rem dicta quisquam error? Enim, neque beatae dicta quo esse, repellendus ipsum blanditiis labore porro id nemo dolores error numquam! Ex, recusandae modi.
        Nulla sit maxime perferendis blanditiis dolorem ratione commodi odit repellat tenetur est consequatur, nihil temporibus placeat totam omnis architecto. Quos unde, harum magni eligendi enim itaque at! Velit, exercitationem aut!
        Ratione asperiores quibusdam, fuga reprehenderit dolorum sit vero odio, beatae maiores eum minus. Enim fugiat, quis officiis nemo sit distinctio asperiores minus id ipsum adipisci itaque corporis impedit beatae ratione!
        Quia laboriosam fuga maiores dolore porro consectetur id, modi enim aut quasi cupiditate qui voluptate amet eaque, labore perferendis obcaecati quibusdam beatae error saepe sunt eum. In quo quos cumque.
        Suscipit quia odit eligendi atque sequi veniam saepe cupiditate? Numquam error recusandae quidem beatae veniam quaerat magnam. Nulla ipsum at modi ab! Non repudiandae tenetur ut ratione laudantium necessitatibus molestias.
        Accusamus ipsam quo, ex earum delectus at, nisi eius laborum reiciendis nesciunt perferendis nemo quod cupiditate quas, minus dolorem dolores. Numquam possimus eligendi voluptate dicta veritatis quidem consequatur sit aliquid.
        Minima rem soluta, exercitationem in, repellendus odio expedita voluptas nemo laudantium ipsum reiciendis blanditiis, rerum distinctio corporis magni atque magnam quia quidem! Debitis, obcaecati eum tempore eaque dolorum voluptas corrupti?
        Architecto molestias odio tempora illo vero eveniet nam, animi fugit excepturi dicta soluta laboriosam officia! Molestias itaque illo voluptatum placeat sequi in dolore quas illum dignissimos vero, consequuntur nihil ratione.
        Eaque velit dolorum optio reiciendis commodi possimus animi laudantium hic sit, ex voluptatibus pariatur voluptate veniam quia molestias nulla nobis. Autem error consequuntur delectus nesciunt aliquid laboriosam ipsam assumenda quas.
        Dolores numquam dignissimos mollitia id doloribus libero recusandae consequatur vero nesciunt. Accusamus error reprehenderit harum maiores deleniti perferendis iusto quod eius praesentium optio. Obcaecati animi excepturi velit laboriosam, dolor accusantium.
        Magnam aut minima, sit cupiditate ipsum quasi numquam quis labore delectus, corrupti nulla consectetur ad. Officiis, aliquid illum modi sed error assumenda. Reiciendis, labore! Eligendi delectus perspiciatis at voluptas voluptatibus.
        Ipsam corporis, consectetur qui fugit vel aliquid perferendis dignissimos, mollitia id ipsum ad eum earum nemo assumenda? Blanditiis, quidem? Harum dolore atque architecto dolores iure corporis voluptates exercitationem facere doloremque!
        Neque quis provident architecto eum labore, nesciunt maiores ipsum blanditiis magnam corrupti quisquam aspernatur, dolor eos nam saepe ducimus natus eius similique, ea et amet deserunt soluta voluptatem repellendus? Odio!
        Tempora impedit placeat voluptatem iure, quas architecto ullam aspernatur quis aperiam illum excepturi repellat officiis cumque dolorem beatae quisquam. Necessitatibus nobis tempora ipsum ipsa animi accusantium dolorem dolor excepturi temporibus?
        Error assumenda aliquid corrupti aliquam, possimus deleniti! Accusamus explicabo voluptatem corporis, corrupti adipisci non veritatis harum perspiciatis atque autem dicta exercitationem amet officiis omnis, saepe aperiam quisquam cupiditate odio iste?
        Hic, id ex repudiandae deserunt magnam dignissimos atque quis cupiditate rerum veritatis? Quod ipsa perspiciatis eos repudiandae magni velit ipsam nemo magnam facere inventore. Tempore aperiam totam eum minus dolorem?
        Provident vel atque iste mollitia repudiandae vero perferendis hic explicabo neque sed nihil praesentium ullam officiis eius architecto, nam blanditiis vitae! At consequatur fuga hic quidem rerum explicabo id dolore.
        Reprehenderit saepe, aliquid repudiandae dolorem iste repellendus vitae, accusantium eaque nesciunt autem accusamus sequi adipisci similique nihil dolores ea tenetur nostrum. Illo minima dolore eos mollitia nobis eum beatae illum!
        Voluptatibus at voluptates quod esse quae temporibus harum quo quidem, natus nihil possimus, nisi iusto ea laudantium? Nulla illum, accusantium repellendus perferendis accusamus impedit deleniti fugiat, provident perspiciatis corrupti amet!
        Beatae eius id perferendis nemo recusandae repellendus, aliquam alias maiores a ad voluptate laudantium quod possimus praesentium nisi consectetur dolorem. Optio omnis expedita at adipisci molestiae doloremque officiis ducimus ipsa.
        Blanditiis, delectus. Veniam et in sit fugit molestiae delectus corporis sunt tempora. A aperiam beatae quod, ipsa doloremque quisquam officia, dolorum maxime rem, pariatur incidunt suscipit voluptatem! Dolores, quo voluptatem.
        Praesentium voluptates itaque quod sed a, similique aliquid fugiat tenetur? Id quisquam, consectetur doloribus ea in quo deserunt illum ad neque numquam nulla praesentium officia delectus magni odit natus saepe?</p>
    </div>

@endsection
